### ISSUE TITLE
error: 'SSH_BIND_OPTIONS_IMPORT_KEY' undeclared

### ISSUE THREAD

**Issue by seamusabshere** [tmate-io/tmate-ssh-server#52]
when building on Alpine:

```
tmate-ssh-server.c: In function 'prepare_ssh':
tmate-ssh-server.c:349:29: error: 'SSH_BIND_OPTIONS_IMPORT_KEY' undeclared (first use in this function)
  ssh_bind_options_set(bind, SSH_BIND_OPTIONS_IMPORT_KEY, rsakey);
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
tmate-ssh-server.c:349:29: note: each undeclared identifier is reported only once for each function it appears in
```

appears to be caused by #47 #49 or #50 because this error does not appear with 8b294f32700a97ea69a6a29e2d8c38963ff3d994

**Comment by amasson84** [comment]
This appends because your libssh is too old.
`git clone https://git.libssh.org/projects/libssh.git libssh`
ant then
`cd libssh && mkdir -p build && cd build && cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DWITH_EXAMPLES=OFF -DWITH_SFTP=OFF .. && make && make install`
and it will work :)

**Comment by nviennot** [comment]
I'm now keeping up to date docker images: https://hub.docker.com/r/tmate/tmate-ssh-server
